---

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi
  vars_files:
    - "vars.yml"

- hosts: k3master
  become: yes
  roles:
    - role: k3s/master
  vars_files:
    - "vars.yml"

- hosts: k3node
  become: yes
  roles:
    - role: k3s/node
  vars_files:
    - "vars.yml"
