---

- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    - role: raspberrypi

- hosts: k3master
  become: yes
  roles:
    - role: k3s/master

- hosts: k3node
  become: yes
  roles:
    - role: k3s/node
